# Generated by Django 3.1.7 on 2021-03-31 18:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.year')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(editable=False, upload_to='thumbs/')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.year')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.year'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'year')},
        ),
    ]
