# Generated by Django 3.1.7 on 2021-06-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videothumbs',
            field=models.ImageField(default=1, editable=False, upload_to='videothumbs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=244),
        ),
    ]
