# Generated by Django 3.1.7 on 2021-06-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210611_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videothumbs',
            field=models.ImageField(editable=False, upload_to='vidthumbs/'),
        ),
    ]
