# Generated by Django 3.1.7 on 2021-06-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210611_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(editable=False, max_length=244),
        ),
    ]
