# Generated by Django 3.1.7 on 2021-06-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210611_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='youtube_video_url',
        ),
    ]
