# Generated by Django 3.1.7 on 2021-06-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
